import { nanoid } from 'nanoid';
import type { Analysis, Perspective, ProgressEvent } from '../types.js';
import { PERSPECTIVES } from '../types.js';
import { save, get } from '../store/index.js';
import { runPerspective, runCodexText } from '../agents/codex.js';
import { validateFragment, composeDocument } from '../utils/html.js';

const listeners=new Map<string,Set<(e:ProgressEvent)=>void>>();
const controllers=new Map<string,AbortController>();
export function subscribe(id:string,fn:(e:ProgressEvent)=>void){let set=listeners.get(id);if(!set){set=new Set();listeners.set(id,set)}set.add(fn);return()=>{set!.delete(fn);if(!set!.size)listeners.delete(id)}}
function emit(e:ProgressEvent){listeners.get(e.analysisId)?.forEach(fn=>fn(e))}
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function pool<T>(items:T[],limit:number,worker:(x:T)=>Promise<void>){let i=0;const runners=Array.from({length:Math.min(limit,items.length)},async()=>{while(i<items.length){const x=items[i++];if(x!==undefined)await worker(x)}});await Promise.all(runners)}

export function cancelAnalysis(id:string){const c=controllers.get(id);c?.abort();controllers.delete(id)}

export async function createAnalysis(name:string,prd:string,selected:Perspective[]){if(!selected.length)throw new Error('Select at least one perspective');for(const p of selected)if(!PERSPECTIVES.includes(p))throw new Error(`Invalid perspective: ${p}`);const now=new Date().toISOString();const a:Analysis={id:nanoid(),name:name||'Untitled PRD',prd,selected,status:'queued',runs:{},createdAt:now,updatedAt:now};for(const p of selected)a.runs[p]={id:nanoid(),perspective:p,status:'queued',attempts:0};await save(a);controllers.set(a.id,new AbortController());void execute(a);return a}

export async function execute(a:Analysis){a.status='running';a.updatedAt=new Date().toISOString();await save(a);emit({type:'analysis.started',analysisId:a.id,message:'Codex agents are starting'});
 await pool(a.selected,Number(process.env.MAX_PARALLEL_AGENTS||6),async p=>{const run=a.runs[p];run.status='running';run.attempts++;run.startedAt=new Date().toISOString();await save(a);emit({type:'agent.started',analysisId:a.id,perspective:p,message:`Codex ${p} agent started`});try{const result=await runPerspective(p,a.prd,e=>emit({type:'agent.event',analysisId:a.id,perspective:p,data:safeEvent(e)}),controllers.get(a.id)?.signal);const validation=validateFragment(result.html);emit({type:'validation.completed',analysisId:a.id,perspective:p,data:validation});if(!validation.ok)throw new Error(validation.errors.join('; '));run.html=result.html;run.threadId=result.threadId;run.status='completed';run.completedAt=new Date().toISOString();await save(a);emit({type:'agent.completed',analysisId:a.id,perspective:p,message:`${p} completed`});}catch(err){run.status='failed';run.error=err instanceof Error?err.message:String(err);run.completedAt=new Date().toISOString();await save(a);emit({type:'agent.failed',analysisId:a.id,perspective:p,message:run.error});}});
 const completed=a.selected.filter(p=>a.runs[p].status==='completed');
 if(a.status==='cancelled'){controllers.delete(a.id);await save(a);emit({type:'analysis.failed',analysisId:a.id,message:'Analysis cancelled'});return}
 if(!completed.length){a.status='failed';controllers.delete(a.id);await save(a);emit({type:'analysis.failed',analysisId:a.id,message:'No perspective completed successfully'});return}
 try{emit({type:'composer.started',analysisId:a.id,message:'Codex Report Composer is assembling the final HTML…'});const sections=completed.map(p=>a.runs[p].html!).filter(Boolean);const composed=await composeWithCodex(a,sections);const critic=await criticWithCodex(a,composed);a.critic=critic;emit({type:'critic.completed',analysisId:a.id,data:critic});let final=composed;if(critic.status==='needs_refinement' && Number(process.env.MAX_CRITIC_REFINEMENTS||2)>0){final=await refineWithCodex(a,composed,critic)}else{final=composed}a.finalHtml=final;a.status='completed';controllers.delete(a.id);a.updatedAt=new Date().toISOString();await save(a);emit({type:'composer.completed',analysisId:a.id,message:'Final HTML report assembled'});emit({type:'analysis.completed',analysisId:a.id,message:'Analysis completed'});}catch(err){a.status='failed';a.updatedAt=new Date().toISOString();await save(a);emit({type:'analysis.failed',analysisId:a.id,message:err instanceof Error?err.message:String(err)});}}

async function composeWithCodex(a:Analysis,sections:string[]){const prompt=`You are the Codex Report Composer. Assemble a coherent final UX report from the supplied HTML sections. Preserve useful detail, reconcile obvious terminology inconsistencies, do not invent facts, and keep each perspective recognizable. Return ONLY a complete HTML document with inline CSS. The document must be safe, accessible, responsive, and scrollable. Do not include scripts or external resources.\n\nPRD:\n${a.prd}\n\nSECTIONS:\n${sections.join('\n\n')}`;const r=await runCodexText(prompt,e=>emit({type:'agent.event',analysisId:a.id,data:safeEvent(e)}),controllers.get(a.id)?.signal);return normalizeDocument(r.text,a.name)}
async function criticWithCodex(a:Analysis,html:string){const prompt=`Act as a UX report critic. Review this final HTML report against the PRD. Return ONLY JSON with fields status (ok|needs_refinement), summary string, issues string[]. Find contradictions, unsupported claims, missing major requirements, broken structure, unsafe HTML, or weak traceability. Do not invent issues.\nPRD:\n${a.prd}\nREPORT:\n${html}`;const r=await runCodexText(prompt,()=>{},controllers.get(a.id)?.signal);try{const parsed=JSON.parse(stripFence(r.text));return {status:parsed.status==='ok'?'ok':'needs_refinement',summary:String(parsed.summary||''),issues:Array.isArray(parsed.issues)?parsed.issues.map(String):[]}}catch{return {status:'ok',summary:'Critic response was not machine-readable; report retained.',issues:[]}}}
async function refineWithCodex(a:Analysis,html:string,critic:{summary:string;issues:string[]}){const prompt=`Refine the HTML report using only valid critic findings. Preserve all correct content. Do not invent requirements. Return ONLY a complete HTML document.\nPRD:\n${a.prd}\nCRITIC:\n${critic.summary}\n${critic.issues.join('\n')}\nREPORT:\n${html}`;const r=await runCodexText(prompt,()=>{},controllers.get(a.id)?.signal);return normalizeDocument(r.text,a.name)}
function normalizeDocument(raw:string,title:string){const clean=raw.replace(/^```html\s*/i,'').replace(/^```\s*/,'').replace(/\s*```$/,'').trim();if(/^<!doctype html>/i.test(clean)||/^<html\b/i.test(clean))return clean;return composeDocument([clean],title)}
function stripFence(s:string){return s.replace(/^```json\s*/i,'').replace(/^```\s*/,'').replace(/\s*```$/,'').trim()}
function safeEvent(e:any){return {type:e?.type,itemType:e?.item?.type,text:e?.item?.type==='agent_message'?e.item.text:undefined}}

export async function rerunPerspective(a:Analysis,p:Perspective){if(!a.selected.includes(p))throw new Error('Perspective is not part of this analysis');a.runs[p].status='queued';a.runs[p].error=undefined;a.updatedAt=new Date().toISOString();await save(a);void executeSingleAndRecompose(a,p)}
async function executeSingleAndRecompose(a:Analysis,p:Perspective){const run=a.runs[p];run.status='running';run.attempts++;emit({type:'agent.started',analysisId:a.id,perspective:p,message:`Re-running ${p}`});try{const r=await runPerspective(p,a.prd,e=>emit({type:'agent.event',analysisId:a.id,perspective:p,data:safeEvent(e)}),controllers.get(a.id)?.signal);const v=validateFragment(r.html);if(!v.ok)throw new Error(v.errors.join('; '));run.html=r.html;run.threadId=r.threadId;run.status='completed';run.completedAt=new Date().toISOString();await save(a);emit({type:'agent.completed',analysisId:a.id,perspective:p,message:`${p} regenerated`});const sections=a.selected.map(x=>a.runs[x].html).filter(Boolean) as string[];const composed=await composeWithCodex(a,sections);a.finalHtml=composed;a.updatedAt=new Date().toISOString();await save(a);emit({type:'analysis.completed',analysisId:a.id,message:'Report recomposed'});}catch(e){run.status='failed';run.error=e instanceof Error?e.message:String(e);await save(a);emit({type:'agent.failed',analysisId:a.id,perspective:p,message:run.error})}}
